### ISSUE TITLE
Alpha release

### ISSUE THREAD

**Issue by yann300** [ethential/code-remix#9]
This list all the issues that could be integrated to the alpha release:

 - [x] improve the css theme (will benefit both solhint and sourcify)
 - [x] solhint: sometimes highlights aren't removed (although the solhint tab doesn't display any warning)
 - [x] sourcify: adding a file (metadata.json) throws an exception (permission)
 - [x] sourcify: seems it doesn't listen on compilationFinished.
 - [x] we should keep in the list only the plugin that are actually working.
 - [x] the log (error, warning and logging solidity version) of the compiler could be improved (so it's easier to find and fix errors).
 - [x] see which other plugins could be eligible for this beta release.

EDIT 29/01:

- [x] the sourcify plugin displays the absolute path (see screenshot below). Path given to plugin should always be relative to the workspace.
![Screenshot from 2021-01-28 16-56-39](https://user-images.githubusercontent.com/6940742/106164111-f001dd80-6189-11eb-9c40-f7cfd45d44a2.png)

- [x] source highlight doesn't work anymore (solhint plugin). 
- [x] when a plugin tab is closed or when plugin is deactivated, source highlight should be removed, is this the case already?
      => probable solution for solhint: `click on a warning, will highlight for 2-3 and automatically unhighlight`
- [x] sol2Uml: after having compiled and switched to sol2uml, a loading icon is displayed, is that from vscode?

**Comment by 0mkara** [comment]
>  sourcify: seems it doesn't listen on compilationFinished.

Latest version of sourcify does. Although there is an issue with `sources`.

**Comment by 0mkara** [comment]
- [x] add, run development plugins

**Comment by 0mkara** [comment]
~`getCompilationResult`  is required.~

**Comment by bunsenstraat** [comment]
List of plugins with plugin-webview > 0.3
dGit +
solhint + 
sol2uml +
learneth +
sourcify +

**Comment by yann300** [comment]
@0mkara 
I think `dGit` requires the file manager to emit some events which are not implemented in vscode (please ask @bunsenstraat about what is needed). We could have this later though.

`solhint` is already in vscode but we are using an updated version, could you have use it https://github.com/ethereum/remix-plugins-directory/blob/master/plugins/solhint/profile.json#L7 ?
`learneth` can't be  used right, now we miss the `solidityUnitTesting` plugin.
`sourcify` is already there.
`sol2uml` can be a nice add.

**Comment by yann300** [comment]
some other comments since last check:

- [x] the sourcify plugin displays the absolute path (see screenshot below). Path given to plugin should always be relative to the workspace.
![Screenshot from 2021-01-28 16-56-39](https://user-images.githubusercontent.com/6940742/106164111-f001dd80-6189-11eb-9c40-f7cfd45d44a2.png)

- [x] source highlight doesn't work anymore (solhint plugin). 
- [x] when a plugin tab is closed or when plugin is deactivated, source highlight should be removed, is this the case already?
- [x] sol2Uml: after having compiled and switched to sol2uml, a loading icon is displayed, is that from vscode?

**Comment by 0mkara** [comment]
> when a plugin tab is closed or when plugin is deactivated, source highlight should be removed, is this the case already?

I have already added this ability when a plugin is deactivated. But when it is closed then it does not work as no event is fired.
